Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'drivers')

# add the general drvers.
src = Split("""
board.c
bsp_rtc.c
stm32f10x_it.c
adc.c
rs485.c
led.c
key.c
""")

# add Ethernet drvers.
if GetDepend('RT_USING_SPI'):
    src += ['spi_flash.c']
# add Ethernet drvers.
if GetDepend('RT_USING_I2C'):
    src += ['i2c_ee.c']

# add Ethernet drvers.
if GetDepend('RT_USING_SERIAL'):
    src += ['usart.c']

# add Ethernet drvers.
if GetDepend('RT_USING_LWIP'):
    src += ['dm9000a.c']

# add Ethernet drvers.
if GetDepend('RT_USING_DFS'):
    src += ['sdcard.c']

# add Ethernet drvers.
if GetDepend('RT_USING_RTGUI'):
    src += ['touch.c']
    if rtconfig.RT_USING_LCD_TYPE == 'ILI932X':
        src += ['ili_lcd_general.c']
    elif rtconfig.RT_USING_LCD_TYPE == 'SSD1289':
        src += ['ssd1289.c']
    elif rtconfig.RT_USING_LCD_TYPE == 'SPFD5420A':
        src += ['spfd5420a.c']

# add Ethernet drvers.
if GetDepend('RT_USING_LCD'):
#    src += ['touch.c']
    if rtconfig.RT_USING_LCD_TYPE == 'ILI932X':
        src += ['ili_lcd_general.c']
    elif rtconfig.RT_USING_LCD_TYPE == 'SSD1289':
        src += ['ssd1289.c']
    elif rtconfig.RT_USING_LCD_TYPE == 'SPFD5420A':
        src += ['spfd5420a.c']
    
CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
